version: "3.9"

services:
  database:
    image: postgres:14.2
    restart: unless-stopped
    container_name: psql
    ports:
      - "5432:5432"
    env_file: .env-sample
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      timeout: 15s
      interval: 10s
      retries: 5
  transfeera-backend:
    depends_on:
      - database
    build: .
    restart: on-failure
    container_name: trasnfeera-backend
    ports:
      - "8000:8000"
    env_file: .env-sample #Make sure the env is filled out
    networks:
      - default
networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local