version: "3.9"

services:
  database:
    image: postgres:14.2
    restart: unless-stopped
    container_name: psql
    ports:
      - "5432:5432"
    env_file: .env-sample
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      timeout: 15s
      interval: 10s
      retries: 5

networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local